---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chore-quest-secret
  namespace: chore-quest
spec:
  encryptedData:
    nextauth-secret: AgCELxMT1H0mxeFldsBTTC98cjwhqO7IZWYyfiWccdKWKPtGJuPavtxPN/IdFtFYPvAftEtVBgb1h9Ri5ZWVRqO+OD8gGNsIz1XDDMXRmGblfQh1hLGwU0D4/UqMVdJNiyUiTyMhb8380iDjmpIlT21nDZhRrloUSoyAhZVXePPkOy3jik4wS9nOtmja++Q7ZjTyadtt5x5LadXhjq8cPx0H2+yNaoQ7qc6ny+Prf8VLPvhgqmnWUFSmV387Ws95zFPFBQUaQtcQU7NkAfJ7NCPzEF1nEVzNKf/OrUdnaqaV6mK5tZofWZiB8T6hnHVFrCx5OA0M7JTwjLPgFlzXi/4qQ1KJMDVtiMQTRAkD4NpMiYS2oMKhgm7A/QPD1/P7qPIXKN+XBBg3UjdDaVb4cG8O/MDzlXdbCnn5Iuv4HWGyaUco66hIj8hEkPZJndVgGTJWUK8UHi/ROWBuJDKM2gj7+52cQE9hNgo7vH8o/wzqh6EVmnn1xvVl9lUnMuURRp22lRkAe82QbrQoZ8PHr4NMGuYf7qnWgb6T4PWIMoCVjbql0O7olCCXOp5Sd5g2rDM7GRAN8UArL2P7Xwdt90p6l4f3HvfaFZU7gGw658m6poBhX84DPUQoLbIXVe60DnrAS1aixhgUA3UCvhStHcNNZm2F8TPbHIBLTI+fXSsIgKMsB9CsdToQsOFaULU+RzKLcTd9g3JFlSihUJZUp7OoyDQhZZiuDVQiYwD2oqXjAVXbUVnJ45VrL8031w==
  template:
    metadata:
      name: chore-quest-secret
      namespace: chore-quest
