---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: chore-quest
spec:
  encryptedData:
    .dockerconfigjson: AgAXfK4ePyGss0Mfklq65VvtGDGkD4mG6ao3eU/1pzy2fp/N97vGz0txLKbfa5Fg3CNx1UZd1Gnqj79bHnICtCSmKfDgDe/LgriDXlT6ROllgC9Cuni81tpBIBG5ahR8eH7viHkqCp987YV3nM9+o5JeZAFSOxRFjldYzXUDUBD/PDPhWW8zJGfzf0T+paLEsbMZCYV5JJJzXM0QHNBVQbi6ef1rnQeYVH2ItzYEw0jnWJrAqQkyxkbfsXVFN8qnurmKkbg+zLtx93KCAYZjS9K/DfphSNCjHKZzR4LFreOnWr2T1aLVM5ZYD3D3tUJwthRS5Yl2pNh/PBwB5YLkStGHsAvsgmuG0i4wtpLc7DIGyu+laO7cf/9pGfI0//jTLOE1tsvRaQ4m6bh1YxmtEFP0BlBmpGB8guSdxtCZYKNe/KkJNhI2X014XgSckqKtYycHmVNNs5LIFepY9DqWIlWylCHxNAdU5EDhbb1My/y9jSlS2VOjPqWFpgY75s13oACIN7zRprRnsNtGDkoljNm/WDVeFcDtRmyNJgfmjHkyORriHwNxYmaprpijvUqvX1oY3orEOrpERtx2trZRbRS2+cDfugnAC+MT+/6mz87TkGlhhcxXdHr+sziL97eoPdNewThmwGJsYXt/5jHTiqhiaw3kML0q7VMOpQ2TjsCHIsAnDDzBx9e/gm20BLn47bufLoS9gjk5QVPvuluoUWkUN17rzxuLm3iInbhFuom432ensmFxTH5aZMmDg5brS19Ymf0Zh97Bn0qVxWOKK+hIh8fePoxR/M7prLiWt7FjHO1mqFrIIXe0JhQQtvqhyHdWovUtOdUDMDvtWsHsErTE+J6upj1IpT1HP4fDY0tdEIdXG/RkYYyCQZJHT+4cszcUbsu2RyYWw/Pn5RY+y7/an/2HoYoQAQSjXRwsoqLg+tY=
  template:
    metadata:
      name: ghcr-credentials
      namespace: chore-quest
    type: kubernetes.io/dockerconfigjson
