---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: chore-quest
spec:
  encryptedData:
    .dockerconfigjson: AgBP30bAye8tHZlHoXFqDnf53t/zJZvfGsiRfiYssUG8Kx5Ss5tzxOwjfsHv1eHKWHznVRlTTQMQmeq8IE8aGg3coHMz2yMQyavt5KrufHO+OOHoWqcdy6hj1YTMOxonr4DQdKa81/ijraxbzSg6ed3LuwghMIJFKasHkouceT6DhvUsE/HIMj7ellidwZ2GT3fpMqUpy/1RfuAKnGFkuwsmWAYVdyZsgzGlnnW8Z/k+q0XuFXRh/gGJN/BUTql4+iuP4GLIE93M2J1i2dRdfIVAW0999UWRtTyk1ICZkuQBSGicMIHcx1W1ph8ReKKgkmm6Hkt58GRe9TjfFO4/O/viHD9a0SLTuSGfM+iuD98v886pfgfypY7z9rGRxN2lcVLAKZpu49R/e3sUGfBP5GQ66BWNJ0PZ82S/VTTaFtOjQAczCcK/KDJNsTNpx3eyQpbMft1/DNp1lE07lXAYTrixJAuXnNm6ldGbh9v9UrevgktVPaU1hkO53cUTH4swcv+pWYh+T5SRRon2i8yJaghSkAfbf9O4ntuSzvMCl+faISRBnVKZlt1aVbHiKAD09beKSytbMLLYADD8WTwv+agrA++L6ybfT/ku9N0W0ss/kfQ5mU3oFDEGhH/ZC5NygvIaSHZ6D/MLsBU1q6m69mDitHGr4DLMJwXLfLRQmk/b48Gekajz6ivoYrF0i+u2FMpCP5aQTGVDClr5t6LIb0p+5baqUzLzkDZrl//4lKnEyC1n5YVQ/mJZicOi9SGDX5DyG04UXUb9yRCxVNULnXpW6mySUdAWyGp40wzSi9GsMuSRfTErwzPq5Ktr2zoM0yrQ5/p6vWk6pWNxAuvJ6M9lQfnN7xn29TQGbPOxQsiKFf1XVLAB9K4ZIXMYvy5HGLdJ/E6NOIJYdHZpyU6K/XjSypKpXQKUalJ4yxz/vQUGEcI=
  template:
    metadata:
      name: ghcr-credentials
      namespace: chore-quest
    type: kubernetes.io/dockerconfigjson
