---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    api-token: AgCFMPUQGIk5rUoq53GVENorC4sU2QXYfKTlMEg4Uk+KITXUJQf5Imw35Avssrwh1cDdaiVE/GzhtQJcoRveQSBNeoDdgr2d6+/GVHDJsoukm9H5FYJFWQpHKI7sq8ANHDXo9gAcv77Kd7iRfX0bEWiDTSa5axf514ctgT4IZEg0U+ilz7m9yUXvIzM1rA7CvhDahRSlLj0w6YUwaxtI5ZVeAQsUCh8sI/pyZ93TBOCLkRw+fM9ZdAFtpi4BrqPFFuFb2/GtVljcqLudm3RU81xwHt4n+qQ1QhGwhNxGiSpKPPDdBMmISVCc1csCUPbF0Oj/EMaUooRIMl/AxniV/5kcgCMw+xNOpM/QLsm9Lk6a4U9sGeUpHSunwlL6VjZLUrk9UyoUBHzSIL+7ipCqNY+LcxADmu1ksOSBlDW2OTG0db7FusE6gmluLT1/lxJOe/nRmJIl3BYEbMbMsRzTpYSqhbtpHEqlhytioY9molYg6fmbfq4yCgIGxYDQCWxR/TrRUabzz90OplYdRKndDHaUWOTktdUL7SSP3KmEyEqPRbyKSkf8kCkfnc3/tRCLsX8p8NM0tnMOK/5444LajYyW9ZcjJtcCnZoR3uM/LyNPQUHjngBvQCHJyv9kmeu61TAxv6CHZ6OuJNur4KybEruLjVJ6awCpGB4w+MvN2UlWgeGvLSgvhL6FGDWieFuYk/Ty2uIys3rBHuSjss+ZKjzJjwoHIBqOcqp78guiPViTvbtYHcQBDoSp
    cloudflare-account-id: AgAJR0D/DhW7bFrGblbXR5qRJB+E5uRLDFakVMQtO/jRTfeHWfY/nTteFgxgISCH4AAZqFAvhNERgDrlv7DhqcIiQBAZB5kjnvknDK/prRicIymnj0zvcecetkIjZgqMz3z8uK5ohKORqL1Bc2XOJ1zKD+36ZAeHdMHqi5aiqMCDwrCyobOBIFsWgG4jXyJwEKDEWBS+Tog7WBv2vDWqv8mPhC5QtYE+Ub3sySoIg3hoJLqvgA7aCQ5cDBDg30kFZBn8Wdif9wW9MoSp6xI7EIFYhuCWS0otoPz6yvGj5+6vtqNJVpAnB8G2h8X0HqStj7UkxryKqeeVGH69KIpjkP5+Rs7hePuDbC7K2BIBbsr2LO2v0O2NAU1zGYlsFIi8gqGvgDXI/RcRDj/aHrqww3HYEFQEM4+B0U9A0lNl2RdzicbmFLeUMuFlWbA55nXJsBrK8XAKRzo/afbU5sV31TpX+WTmnS33ize0WuQEyl/SjvnxpZbRaumx8OEX1vZrLRCx24gyqRGCDaIOWt1856gIwyu3vTAhPc/8eN6hCBcYM+byqkkOdYWFHy887OQVWJ9Pd7whbPdt2uw8T5gMVHF/CAZ3SwCGfBcC3pGyEZUMzQiQHFU6n0YodivVVSYWFIe+di2ySa6B2T6TGhQeIzgc5Z4LwrPUq48qSq6y8smzgab133wAAxelVIfAkhO3ksE0rYVO+LZbW9rvzOarJTk5yr9LSRj8S3sD4kS07laTNA==
    cloudflare-tunnel-name: AgCC3SJxqLUtiS1YbO8teJYld1/X7ZQdxJYWNwdghTU7ItlZfzs8VP01KDlD6ThIhoF+dnxjeLe0eYLzBJCZ6252mdlmwuivhejfYI7tuw8NWKhlIRZPz4tnxzwijl8VcEjZDZV5mr6Q53LUvq6/d5s2IQ012JJVehOndH6ItoE34byi1VWo3saFdIYi4EkkVaKQRilZH2MpOKdwUV8HBlr0fXj9zsDojJ88Q8UswCUx+dcMuonkBFYSJuEELIXSCsSfIlDbdH2UeK1YuVazCgm+OzC03N7frv2ZxTKP03dGuRdVOJU/dfbzk7SZ2qUsqstk63xMNoF6PE8JOVW4BQozXfPnrN7A+fHvNwyaNTFDcRWWwhZOj1N2jn9fEVJJVhJc7Tgq5inOGNe6qVgG0KhFW6UODhATZwovK9OxgavGQSM9uaCUH9DDxvawI+a57IYiNkNMBs6wWhsONUO+L3Y+PWm6J/PA3OJv5LozgVs6BXkevzNu3XDhpPeVis/uZ7szTa0+qqP5+r6fDRea0vdaH/CJu4WbyppY6YZSDlX2YfTgYDCetL4bPjeNrBSsOrxL9ZJURwtPveVeLZGkTS8bhf3c50f4Z+ijErUCIVR767wI5m9RuN//TrQtsjBcGaqaiwrdtdDYAuN6yTg593CBPCvIi+H1YqI3E0RaYfSC8ForJlR39gxsPM+PBFut+sy1MRNydjhy96INjJP9/w==
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: cloudflare-tunnel-ingress-controller
        meta.helm.sh/release-namespace: cloudflare-tunnel
      creationTimestamp: null
      labels:
        app.kubernetes.io/managed-by: Helm
      name: cloudflare-api
      namespace: cloudflare-tunnel
    type: Opaque
