---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-secret
  namespace: datadog
spec:
  encryptedData:
    api-key: AgA6bZzDkVhAvvzPIFBO5c/N8opKdgfi4ROR+2wKAu8YV47Ju/FcgfPYLMWnee6Cyda7ICVFs9q2NkI8jmgocYoHS+a3P1zglzVbPAwSwEEKDL/z7vLgVputDxLw+C786X3q7CVZAH76m7DpwP2FYcJ6kF8sqWJbW3r8IZ2pQydcKnHbozPT2PSpZZXwTToB3giD58+XrKY4ZzmlsRVOHkuoWK1B5mXDm1OFxu4PK3tu2vaSALHjilSBDLgG5T5FjjYa/HGK91eTrTndAci7bv3EfrV0dLbFuwccAJKuGMpBCJLfGNnnSQBjJ0hQ1uYUI9zvrtv46PfPABC5OFcmCz52oB5YDgzL1oUJYrQbogZ3rXzZdO7jktnnweERYKw8U2N7WJErEdgWEJouSzM/smVqPHGdMN7JMxI/4Exd14LT5D8X4FVYZSgpM+vHRuoBmakFoFkOh5HyOfyA65bow9zcIUdRjjsNdtHimbTDc29TmfwVY2FXjlniVLI5ascnqfb7G7ifKQZwo0O7NYVYpPG6/bLWKcBGgL87oK93Q2WjphKnE+pOiN/ei37eu5sHvdMT9JNG/NoFAQrvEzLGjfVD6+AHUDdNXxGEUYvxxDCWnZC7F3m47h6QgG8BbhDbzFPh6j6n2AJJZ5js4EwmWiUWJD+fJxrTuMjp/wKiPJ6eoKh8Npjr0D0Ek62M4/5K9b/K4zTj0ZTKITH0bUgN8AE8oSZZi+LCXMxYVsB0EnStFg==
    app-key: AgBGXAlieS4jqw9QtDOvenLf5KYtSLQXrppTHuUtfh0IJZrNfizIEX7KDTrHRh0u1Gaw0SOJ/vNGxXO4TPkvbXizm2P8jOzlKt+CO+0vkaIOgOzXt3OTF+65Iaa0/a6NJymEz+nq5z/ejfseeNzDPSJquTTXG1EFLcMf6eRk/S42O6MbT3rRmSriCsVLysB9bLvdqvEOcXsy6cDgoV7cIe9waBXyitgMBKfgFWkN7f7EpyQhXMocbCMjZAEydkQj89wfoDR/AtR2/5GuxmyDCgz8HiK94wBrN3V8VhqQvkUe0IEHBGGiG8YuR7Qoyg/RQoMwEJjYs8ys0cMcycLjNwqc5nX7dDaw9oPoPejsisi1yHr7eYzp5kSUNv8ajHPZGmh01BQelvERq4tS0KLT9/xf/dsd87N0Cxm9bXtvOtgLs47vz3+qkNoLdrUDTJAXfoMUVq9MyvSOQFwhvXkLufN69Du3vReOyV4v5TM8NiR/3qsTm/dnWHiMkOERdrKFh3+qLQ06/6wKJ/mn6/3uC/YWB8u1rbGosETtlPe2mZ4u35moTd1pAh+tt5q+nLMz+R8Xf2lMSf4uVcYeBFDi1JMvH+HJSd/dcBYcFgwwOfclwnWe0W/SSlzN6U+/3d9VfDTEtcIfUit9yw9dmt2y5oqkqKa6iqj4gXbohgIDGSX46QQZZPcOzVJ3cF/nl8vY9MYx2olxTx5M8ZrCbG507tRZ1yF+V5Zuz5nzm9GFC3QrC1DFumxEBulk
  template:
    metadata:
      creationTimestamp: null
      name: datadog-secret
      namespace: datadog
    type: Opaque
