---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vocab-app-anthropic-secret
  namespace: vocab-app-staging
spec:
  encryptedData:
    anthropic-api-key: AgBo/C5S+yO7ffKpnh50SOOktscv+KVlwveqT/E86XA77AzTZHJJ0F0+GwKQpRLXlYxN29AyEGUrT0aYPeQrQRjW9DpUZ/vv5IafDzx5c5FDLM7GdparIdm05gOlZSY/4r/RYmkw0S/uF5bgERxZYHJpCFZKuAmQuNagZfGwoo0pXfN4H02qUbUSRKwRlUXBJvcxzwGQmt3d979IycgiSmjWk5B+dpoiwWMiXiUxSeuc8RatfIgI87rVx3aAu8LH+C55IWemmDQ9VN3Ra0G/jePT1u4885ct6b3pcYZ15GE3cJykUC1zGIgAhp1oBPS50AkAQ0ep6qCPN6CNRs7yRkroG/hCZKSVFjcqZLAy6CVfsfvZ5t4jTA9zBhjshJsiq/9qf8yLqBsXQLdZwcwppP77zD0jNe4sSaVRUzp1r7qJywpYZGZck5r4q4AvhIDsLltGX1VT7G/n+pe/av0lS+93lF8rrSWoGmZPaswAit8BTuv31gBBT5cqAF7YAgt0jW17VB5+dotSiwgPNvLeKtQiHaqqME7ybOADVERxUqlapwD9j6f8S1cUCfCJAxYCN0h++j5NluPOzuVkUWjDzOaue/RSTYv2lJ12am3jQaDek3B5Q6Aj9DqaVlkBiX62QHJHKpy+YeNHWmvlCGlnRnTOWtJQzG3aCZ/+XnYL86UxRAKEOS79HkPdILvOlW4189H6aAM1R94LD+1CczP3WjSp7XuF9NUvd4pz1D6CNeiStTt8sDmPPRoLyH/D5epCZMlRTQ7h+8IuXGLrkXf+Wc2TniSA6TZ7lqCWUZVS1GzDcKN7yxnHfWKW7xdlgVSQAEtH92Vca1a01tqM/VI=
  template:
    metadata:
      creationTimestamp: null
      name: vocab-app-anthropic-secret
      namespace: vocab-app-staging
    type: Opaque
