---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-credentials
  namespace: vocab-app-staging
spec:
  encryptedData:
    .dockerconfigjson: AgB+GyOr/lGnG+OHuKsGHgs7O06gPjUprxGSo6fmgI52W1pIm8SPkOBhtBu34heiCmsNHRTp2MTp9qLQZlhIWo97p9p4lBw5BLbjUrZsLEuNNwpaCSJb66tBlYlZWg++ZCyx28cPRo/brg4J3TcMcQdBwBika/llIpDiNWJ2z9SNz2fEJL0ka58tx6xcqcwHE/bQv01fA0iQO7KSFRJ98ObW4uFNi1AhsZf9kKZNwqJx791kncyXbVvYgKFzbUegAkD2OUuGlaCIwqjwXd0SkEuCHU44Qr7ql6lTY7NvsjMr+5mAG0t9LlP5frFmwqsoQgid8+WITvrhH0U86sFlevef6suZ6chBWuVaETbdElWSkWMOqmj4bxEM+iVcdWEO2sHUBDXpsiiMIzkT6CSQqQ4FYgk5IqRpJriMnBZGNYiq4IdNA/Ji9Z2VkU48m33iRINZzN8B39/CUVW7NcVfl2YqLg7H67btbJ7C1lOizNp3inoirysShwKD15jOSSR8lcZCzjbSFHCyqZAiXTe/EJLaIls0Us2V28Z55mcgvsgzhV+/tUd0DqCdSYw0N3sE8KerPJ48k1pk+lWXrql8fNsuJD1pPqAE/J8AFUfwifvUykuqXn1gYu2MVbVOjDWZhTJY6V2sLcvWVtlorDyXPv+tKOMbkkwcX4qdvEQOJ7H3jsySR8e7eQtOikps42zW0oPU6dTqHo2Du9E7Zb7pP1RJSEoCBq5IIfHGH+KIJN1jQzkgSl/oCxEp7Ze93CfF0yjOlffEl01rfe/MkY7XDIfkPbmJzbV5k+EaxFQ3b/8ncUpeBVYdPWoWr6fAn6AaGnxaCGaaJZK0TrY5re3cHeQ2yVfQnKoMUR4BpmkZqckPkiCrvv3YTB3KgbSzX/8JUt+53vMflcY/NmciUWDhnzU07uwQxy7WC5O7tiAu3jybIJUCBunh0QnTum2jRRZWFXMs+IYw/dFUguzVYAJKLsmCK73crOZ6HOC7zeBmUw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-credentials
      namespace: vocab-app-staging
    type: kubernetes.io/dockerconfigjson
